### ISSUE TITLE
Cue Sheet - cue.coder

### ISSUE THREAD

**Issue by Skif-off** [Lenchik/Akelpad-syntax-highlighting#25]
Взгляните, у кого будет время: впечатление что-то как-то не очень.

**Comment by Lenchik** [comment]
на cue от звуковых файлов смотрится очень даже ничего

Строчки такого плана
```
    REM REPLAYGAIN_TRACK_GAIN -1.31 dB
    REM REPLAYGAIN_TRACK_PEAK 0.761322
```
можно было бы получше подсветить

**Comment by Skif-off** [comment]
Они вообще не подсвечены :) Упустил из внимания, нашёл
```
REPLAYGAIN_TRACK_GAIN
REPLAYGAIN_TRACK_PEAK
REPLAYGAIN_ALBUM_GAIN
REPLAYGAIN_ALBUM_PEAK
```
Вроде больше ничего?

Так попробовать
```
1	"(REM)\s(REPLAYGAIN_(TRACK|ALBUM)_(GAIN|PEAK))"	"\1=(2,${COMM},0) \2=(3,0,0)"
```
или цифры тоже лучше подсветить?

**Comment by Lenchik** [comment]
```
1   "(REM)\s(REPLAYGAIN_(TRACK|ALBUM)_(GAIN|PEAK))" "\1=(2,${COMM},0) \2=(3,${VAR},0)"
```
Мне кажется, так правильней, всё таки это не просто комментарий, а определённый индикатор/параметр.
Подсвеченные цифры можно было бы тоже попробовать.

**Comment by Skif-off** [comment]
Согласен, подсветил и значения, постарался объединить в одно правило (коммит _Add: ReplayGain tags_), так вроде нормально?

**Comment by Lenchik** [comment]
Да, нормально.
По-моему, классно получилось.
У меня нет под боком тех cue, которые с bin файлами-образами дисков рядом идут. чтобы и на них посмотреть.

**Comment by Skif-off** [comment]
Если правильно понял, особых отличий от *.bin нет, разница в типе в FILE:
```
FILE "name.flac" WAVE
FILE "name.bin" BINARY
```

**Comment by Lenchik** [comment]
@Skif-off 
```
REM REPLAYGAIN_TRACK_GAIN +3.14 dB
```
Вот у такого цифры с плюсом не подсвечиваются

**Comment by Skif-off** [comment]
Исправил, спасибо за помощь :)
