### ISSUE TITLE
нестандартные переменные

### ISSUE THREAD

**Issue by Lenchik** [Lenchik/Akelpad-syntax-highlighting#27]
```Файл ahk.coder удалён из http://akelpad.sourceforge.net/files/plugs/Coder/, так как содержит не стандартные переменные. Если список переменных будет приведён к стандартному, файл будет сразу возвращён.```

**Comment by Skif-off** [comment]
Это из-за комментария в конце строки 281:
```
; ${ROVAR}s vs ${VAR}s
```
Не помню, с какой версии плагин Coder начал ругаться.

**Comment by Drugoy** [comment]
Так он же в комментариях только присутствует, если он и на комментарии ругается, то мне кажется, что править надо не с нашей стороны.

**Comment by Lenchik** [comment]
@Drugoy, Инструктору продемонстрируете?
Я так понимаю, что он видит стандартную ошибку, выскакивающую при лишних неправильных переменных и просто из-за этого убирает файл.
Комментарии в конце строк QuotesRE видимо не совсем верно отрабатываются.
Может быть, Вы, как основной разработчик этого файла найдёте оптимальное решение этой проблемы?

**Comment by Drugoy** [comment]
Кажется, проблема появилась после появления новых столбцов в некоторых секциях Coder плагина. Я у себя локально добавил нулевые значения правилам и кажется именно это спасло.
Кто-нибудь может проверить у себя - с последним коммитом вылезают какие-то предупреждения? Если нет, то закройте баг.

**Comment by Lenchik** [comment]
Коммит 6d03b84b1a1f101916332f5e5833b91c007a96b3, похоже, решил эту проблему.
Спасибо, @Drugoy!

**Comment by Lenchik** [comment]
Обновлённый файл Инструктору сейчас зашлю.
