### ISSUE TITLE
PowerPro

### ISSUE THREAD

**Issue by lollita** [Lenchik/Akelpad-syntax-highlighting#32]
Do it is possible to add support for PowerPro?
https://groups.yahoo.com/neo/groups/power-pro

**Comment by Lenchik** [comment]
Links or attaches of PowerPro files (syntax highlatable text files) would be helpful. Also file format description is helpful too.

**Comment by lollita** [comment]
http://notepad-plus.sourceforge.net/commun/userDefinedLang/NPP_Powerpro.zip

**Comment by Skif-off** [comment]
@lollita 
Try [powerpro.coder](https://github.com/Lenchik/Akelpad-syntax-highlighting/blob/master/powerpro.coder). It's the first attempt, I don't like ```NPP_Powerpro.zip``` and I think I will rewrite file.

Syntax is case insensitive, didn't it? Could you add links to typical real examples (firstly examples with ```Clip```/```Exec```/```File``` etc)?

**Comment by lollita** [comment]
Ty.
It work.
Syntax is case insensitive.
links to typical real examples:
http://ppro.totalcmd.net
https://groups.yahoo.com/neo/groups/power-pro/files/Scripts/

**Comment by Skif-off** [comment]
@lollita 
Can you try new [powerpro.coder](https://github.com/Lenchik/Akelpad-syntax-highlighting/blob/master/powerpro.coder)?

Could you add links to script examples with PowerPro built in commands (```Clip```/```Exec```/```File``` etc)?

**Comment by lollita** [comment]
it is as good as it was before.
All objects with the dot are missing.
f.e.:
wait.for
exec.EmptyRecycleBin
trayicon.right

**Comment by Skif-off** [comment]
> All objects with the dot are missing.

This is not true :) All built in plugins is fully.

Now I added new (expression) syntax for built in commands.

**Comment by lollita** [comment]
You did a great job.  It works great.  Thank you.

**Comment by Skif-off** [comment]
Thank you for checking :)

New upd.

**Comment by Skif-off** [comment]
Can I close this request?

**Comment by lollita** [comment]
yes, ty.

**Comment by Skif-off** [comment]
In the next few days I will ask AkelPad author to add coder-file [here](http://akelpad.sourceforge.net/files/plugs/Coder/)
