### ISSUE TITLE
Курсив и жирный текст в fb2.coder 

### ISSUE THREAD

**Issue by cuprum** [Lenchik/Akelpad-syntax-highlighting#33]
При редактировании fb2 файлов текст в кавычках выделяется курсивом и другим цветом. Это странно.
По-моему, уместнее подсвечивать тот текст, который находится внутри подходящих тегов:
`<emphasis>` - курсив,
`<strong>` - жирный.
Обычный текст в кавычках лучше оставить без оформления.

**Comment by Skif-off** [comment]
> При редактировании fb2 файлов текст в кавычках выделяется курсивом и другим цветом. Это странно.

Да, как обычно строки в языках программирования. Это не странно, задумано в помощь валидации, некоторые книги сделаны спустя в рукава: потерянные закрывающие или открывающие кавычки или две одинарные подряд ```''``` вместо двойных ```"``` - не такое уж редкое явление. Плюс вложенные кавычки. Вы же в AkelPad не для чтения открываете? ;)

> По-моему, уместнее подсвечивать тот текст, который находится внутри подходящих тегов:

Они могут быть вложены друг в друга, гемор, да и ни к чему особо.

В общем, пока не знаю, что решить, сама фича была добавлена [почти сразу и достаточно давно](http://akelpad.sourceforge.net/forum/viewtopic.php?p=30580#30580).

**Comment by cuprum** [comment]
> В принципе, в крайнем случае пользователь может просто закоментить правила в Quotes

Так и поступлю :smile:
