### ISSUE TITLE
Structure of .coder files (4autors)

### ISSUE THREAD

**Issue by Skif-off** [Lenchik/Akelpad-syntax-highlighting#37]
@Lenchik, @Drugoy

Решил обновить структуру coder-файлов (комментарии, описание, флаги), вышло [так](https://github.com/Lenchik/Akelpad-syntax-highlighting/commit/e7e141f59d8aec401094d3cd55c1d3e6b60e0b47). Обычно не трогаю не свои, но сделал и подумал, вдруг кто-то из вас хотел использовать обновление в будущем как подсказку про новые фичи (ID и прочее)?
С другой стороны, если кто-то захочет подхватить и пилить coder-файлы, тому будет попроще, если полное описание будет под рукой.

Никто не против, заливаю?

P.S. В ahk.coder сделал как было: обновил описание флагов подсветки и фолдинга и так же обновил перевод.

**Comment by Lenchik** [comment]
Мне норм, да. Можно было пуллреквестом, кстати, сразу делать.

**Comment by Skif-off** [comment]
Залил.
С PR чуть больше суеты и в истории лишнее, а так снёс ветку парой команд и всё :)
